version: '3'
services:
  ubuntu_cuda_12_4_bert:
    restart: always
    build: .
    container_name: 'ubuntu_cuda_12_4_bert'
    working_dir: '/root/workspace/'
    tty: true
    volumes:
      - .:/root/workspace/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
